/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PollIdRouteImport } from './routes/poll/$id'
import { Route as AnalyticsIdRouteImport } from './routes/analytics/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollIdRoute = PollIdRouteImport.update({
  id: '/poll/$id',
  path: '/poll/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIdRoute = AnalyticsIdRouteImport.update({
  id: '/analytics/$id',
  path: '/analytics/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics/$id': typeof AnalyticsIdRoute
  '/poll/$id': typeof PollIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics/$id': typeof AnalyticsIdRoute
  '/poll/$id': typeof PollIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics/$id': typeof AnalyticsIdRoute
  '/poll/$id': typeof PollIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/dashboard'
    | '/error'
    | '/login'
    | '/register'
    | '/analytics/$id'
    | '/poll/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/dashboard'
    | '/error'
    | '/login'
    | '/register'
    | '/analytics/$id'
    | '/poll/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/dashboard'
    | '/error'
    | '/login'
    | '/register'
    | '/analytics/$id'
    | '/poll/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AnalyticsIdRoute: typeof AnalyticsIdRoute
  PollIdRoute: typeof PollIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$id': {
      id: '/poll/$id'
      path: '/poll/$id'
      fullPath: '/poll/$id'
      preLoaderRoute: typeof PollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/$id': {
      id: '/analytics/$id'
      path: '/analytics/$id'
      fullPath: '/analytics/$id'
      preLoaderRoute: typeof AnalyticsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AnalyticsIdRoute: AnalyticsIdRoute,
  PollIdRoute: PollIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
